[package]
name = "jot"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["env", "derive"] }
directories = "5.0.1"
edit = "0.1.5"
rprompt = "2.1.1"
slug = "0.1.6"
