[package]
name = "jot_note"
version = "0.1.2"
edition = "2021"
author = "Quenten Griffith <qgriffith@gmail.com>"
description = "Jot Note Taking CLI"
license = "MIT"
keywords = ["jot", "binary", "notes", "cli"]
readme = "README.md"
repository = "https://github.com/qgriffith/jot-rs"
homepage = "https://github.com/qgriffith/jot-rs"

[[bin]]
name = "jot"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.23", features = ["env", "derive"] }
directories = "5.0.1"
edit = "0.1.5"
miette = { version = "7.2.0", features = ["fancy"] }
owo-colors = "4.0.0"
rprompt = "2.1.1"
slug = "0.1.6"
tempfile = "3.12.0"
thiserror = "1.0.63"
walkdir = "2.5.0"
